language: node_js

node_js:
  - "5.1"

services:
  - redis-server

before_install:
  - cd push-server
  - npm install -g npm@2.7.3

after_success:
- npm install -g istanbul
- npm install coveralls
- istanbul cover node_modules/.bin/_mocha --report lcovonly -- -R spec
- ./node_modules/.bin/coveralls < ./coverage/lcov.info
- rm -rf ./coverage